name: universal_image
description: A flutter package to display all image types for all platforms
version: 0.0.1
author: ductranit
homepage: https://github.com/ductranit/flutter_universal_image

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  extended_image: ^1.1.2
  universal_io: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
