name: universal_image
description: A flutter package to display all image types for all platforms
version: 0.1.7
homepage: https://github.com/ductranit/flutter_universal_image
repository: https://github.com/ductranit/flutter_universal_image
issue_tracker: https://github.com/ductranit/flutter_universal_image/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  extended_image: ^7.0.2
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
