name: universal_image
description: A flutter package to display all image types for all platforms
version: 1.0.0
homepage: https://github.com/ductranit/flutter_universal_image
repository: https://github.com/ductranit/flutter_universal_image
issue_tracker: https://github.com/ductranit/flutter_universal_image/issues

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  extended_image: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
