name: universal_image
description: A flutter package to display all image types for all platforms
version: 0.0.8
homepage: https://github.com/ductranit/flutter_universal_image
repository: https://github.com/ductranit/flutter_universal_image
issue_tracker: https://github.com/ductranit/flutter_universal_image/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.20.0-nullsafety.3
  extended_image: 1.5.0-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
